platform :ios, '8.4'
use_frameworks!

pod 'Alamofire', '~> 2.0'
pod 'SwiftyJSON', '~> 2.3'
pod 'MGSwipeTableCell', '~> 1.5.1'
pod 'MMProgressHUD', '~> 0.3'
pod 'MMDrawerController', '~> 0.5.7'
pod 'Toast', '~> 2.4'
pod 'RSKImageCropper', '~> 1.2'
pod 'SDWebImage', '~> 3.7'
pod 'UIActivityIndicator-for-SDWebImage', '~> 1.2'
pod 'SZTextView', '~> 1.2'
pod 'HexColors', '~> 2.3'
pod 'RealmSwift', '~> 0.96'
pod 'KeychainSwift', '~> 3.0'
pod 'IQKeyboardManagerSwift', '~> 3.3'
pod 'UITextField+Shake', '~> 1.1'
pod 'Sheriff', '~> 0.3'
pod 'TTTAttributedLabel', '~> 1.13'
pod 'iRate', '~> 1.11'
pod 'BSForegroundNotification', '~> 0.1.3'