platform :ios, '8.4'
use_frameworks!

pod 'Alamofire', '~> 1.3'
pod 'SwiftyJSON', '~> 2.2.1'
pod 'MGSwipeTableCell', '~> 1.5.1'
pod 'MMProgressHUD', '~> 0.3.1'
pod 'MMDrawerController', '~> 0.5.7'
pod 'Toast', '~> 2.4'
pod 'RSKImageCropper', '~> 1.2'
pod 'SDWebImage', '~> 3.7'
pod 'UIActivityIndicator-for-SDWebImage', '~> 1.2'
pod 'SZTextView', '~> 1.2'
pod 'HexColors', '~> 2.3'
pod 'RealmSwift', '~> 0.95'